### ISSUE TITLE
EC connection issue with test connection for Azure EC Gateway

### ISSUE THREAD

**Issue by AakritiTalwar12** [Enterprise-connect/sdk#113]
Hi Team,

As discussed in the last call I am trying to connect an on cloud rds instance from my local.
Please find below the details of the connection

1. Client Agent - Running on my local machine.
2. Gateway - on Azure instance
3. Server Agent - Running on AWS EC2 instance.

I have verified the rds instance is reachable from the server agent machine.
while trying to connect I get pending confirmation from the gateway.
but cant get any log on the server side but super connection is intact all along
![Client logs](https://user-images.githubusercontent.com/58229454/83536658-23b03900-a511-11ea-95bd-dd11ade14343.PNG)
![Gateway Logs](https://user-images.githubusercontent.com/58229454/83536727-3c205380-a511-11ea-8076-4760270a31c1.PNG)
![Server logs](https://user-images.githubusercontent.com/58229454/83536744-43476180-a511-11ea-8a03-ef03e37fb2ad.PNG)

**Comment by ayasuda2OO3** [comment]
Investigating. @ramaraosrikakulapu can you confirm and replicate the usage in your setting?

**Comment by palokam** [comment]
@ayasuda2003  @AakritiTalwar12 -  It is a known issue in Azure App Gateway - we've debugged this issue with Azure support team for 2 weeks earlier in April, 2020. They are not able to find the fix for it.

There are 2 solutions
1) NGINX as LB
2) Use Azure Loadbalancer instead of Azure App GW

@ramaraosrikakulapu  tested both previously and share his settings

**Comment by ayasuda2OO3** [comment]
@AakritiTalwar12 close for the solution provisioned by @ramaraosrikakulapu https://github.com/Enterprise-connect/oci/tree/v1.1beta/spec/loadbalancer please give feedback upon the usage.
